[package]
name = "refrs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = {version="4.5.23", features=["derive"] }
dialoguer = "0.11.0"
dirs-next = "2.0.0"
env_logger = "0.11.5"
serde = { version="1.0.216", features=["derive"] }
serde_yaml = "0.9.34"
thiserror = "2.0.8"
